apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  namespace: pipeline
  generateName: start-workflow-
spec:
  serviceAccountName: argo
  entrypoint: start-workflow
  arguments:
    parameters:
    - { name: app-name, value: poc-nodejs }
    - name: repo
      value: <git_repo_full>
    - name: ref
      value: <git_revision>

  templates:
  - name: start-workflow
    inputs:
      artifacts:
      - name: git-repo
        path: /src
        git:
          repo: "{{workflow.parameters.repo}}"
          revision: "{{workflow.parameters.ref}}"
          sshPrivateKeySecret:
            name: bitbucket-creds
            key: id_rsa
    metadata:
      labels:
        app: argo
    container:
      resources: 
        requests:
          cpu: 50m
          memory: 50Mi
        limits: 
          cpu: 100m
          memory: 100Mi
      image: argoproj/argocli
      env:
      args: ["submit", "src/argo.yml", "-p", "app-name={{workflow.parameters.app-name}}","-p",
      "repo={{workflow.parameters.repo}}","-p","ref={{workflow.parameters.ref}}"]
 
  